### ISSUE TITLE
l_result = ::ffs(v);

### ISSUE THREAD

**Issue by xiconxi** [quicky2000/P_gif#1]
`
    l_result = ::ffs(v);
`
quicky_bitfield.h|114|error: '::ffs' has not been declared|

**Comment by quicky2000** [comment]
Could you precise the compiler you are using ?

**Comment by xiconxi** [comment]
mingw32-g++

**Comment by quicky2000** [comment]
OK.
I checked on the web and it seems that ffs is missing in Mingw-32.
Mingw-32 no more evolve but there is a successor call Mingw-64 that is still alive and that seems to implement ffs.
So there are 2 solutions:
Migrate to Mingw-64
or replace quicky_bitfield.h with the attached file and let me know if it solves your issue

[quicky_bitfield.zip](https://github.com/quicky2000/P_gif/files/286147/quicky_bitfield.zip)

**Comment by xiconxi** [comment]
Thanks.

**Comment by quicky2000** [comment]
the modified quicky_bitfield.h solve your issue ?

**Comment by xiconxi** [comment]
Yup

**Comment by quicky2000** [comment]
OK so I will integrate it.
Thanks for the feedback
